# Generated by Django 4.1 on 2022-09-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Patient'), (1, 'Doctor')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='bruh.jpg', upload_to='profile_pics'),
        ),
    ]
