# Generated by Django 4.1 on 2022-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_type_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('a', 'Patient'), ('b', 'Doctor')], default='a', max_length=1),
        ),
    ]
