# Generated by Django 4.1 on 2022-09-27 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0003_alter_illnesstype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('a', '9:00 - 9:20'), ('b', '9:30 - 9:50'), ('c', '10:00 - 10:20'), ('d', '10:30 - 10:50'), ('e', '11:00 - 11:20'), ('f', '11:30 - 11:50'), ('g', '12:00 - 12:20'), ('h', '13:00 - 13:20'), ('i', '13:30 - 13:50'), ('j', '14:00 - 14:20'), ('k', '14:30 - 14:50'), ('l', '15:00 - 15:20'), ('m', '15:30 - 15:50'), ('n', '16:00 - 16:20'), ('o', '16:30 - 16:50'), ('p', '17:00 - 17:20')], max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.illnesstype')),
            ],
        ),
    ]
