# Generated by Django 4.1 on 2022-09-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='type',
        ),
    ]
