# Generated by Django 4.1 on 2022-09-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_illnesstype_options_and_more'),
        ('appointment', '0003_remove_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.illnesstype'),
        ),
    ]
