# Generated by Django 4.1 on 2022-09-12 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IllnessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_prescription', models.BooleanField(default=False)),
                ('is_hospital_stay', models.BooleanField(default=False)),
                ('dose', models.FloatField(default=0)),
                ('hospital_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.illness')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='history.treatment')),
            ],
        ),
        migrations.AddField(
            model_name='illness',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.illnesstype'),
        ),
    ]
