# Generated by Django 4.1 on 2022-09-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illness',
            options={'verbose_name_plural': 'Illnesses'},
        ),
    ]
