# Generated by Django 4.1 on 2022-09-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_illness_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illnesstype',
            options={'verbose_name': 'Illness Type', 'verbose_name_plural': 'Illness Types'},
        ),
        migrations.AlterModelOptions(
            name='medicalhistoryrecord',
            options={'verbose_name': 'Medical History Record', 'verbose_name_plural': 'Medical History Records'},
        ),
    ]
