# Generated by Django 4.1 on 2022-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_illnesstype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='type',
            field=models.CharField(choices=[('a', 'Prescription'), ('b', 'Hospital_Stay')], default='a', max_length=1),
        ),
    ]
