# Generated by Django 4.1 on 2022-09-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_treatment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='is_hospital_stay',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='is_prescription',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='type',
            field=models.CharField(choices=[('a', 'Prescription'), ('b', 'Hospital Stay')], default='a', max_length=1),
        ),
    ]
