# Generated by Django 4.1 on 2022-09-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
